[tools]
## Stack
node = { version = "lts", postinstall = "corepack enable && node -v > .nvmrc" }
deno = "latest"

[env]
_.file = '.env'

[settings]
# Enable extra features
experimental = true
# Ignore idiomatic version files
idiomatic_version_file_enable_tools = []
